version: 2.1

jobs:
  test:
    machine:
      image: cimg/ruby:4.0
    resource_class: medium.gen2

    steps:
      - checkout
      - run:
          command: "bin/test"

workflows:
  build:
    jobs:
      - test
