version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:4.0

    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: "bin/test"

workflows:
  build:
    jobs:
      - test
